/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-26 11:00:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.worker;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.service.db.DBConnection;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.service.db.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Signup - Service Provider</title>\r\n");
      out.write("<script>\r\n");
      out.write("	function toggleExtraFields() {\r\n");
      out.write("		var service = document.getElementById(\"service\");\r\n");
      out.write("		var selected = service.options[service.selectedIndex].text\r\n");
      out.write("				.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("		document.getElementById(\"cookOptions\").style.display = selected\r\n");
      out.write("				.includes(\"cook\") ? \"block\" : \"none\";\r\n");
      out.write("		document.getElementById(\"maidOptions\").style.display = selected\r\n");
      out.write("				.includes(\"maid\") ? \"block\" : \"none\";\r\n");
      out.write("		document.getElementById(\"driverOptions\").style.display = selected\r\n");
      out.write("				.includes(\"driver\") ? \"block\" : \"none\";\r\n");
      out.write("		document.getElementById(\"tutorOptions\").style.display = selected\r\n");
      out.write("				.includes(\"tutor\") ? \"block\" : \"none\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	background: #232884;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border-radius: 16px;\r\n");
      out.write("	padding: 40px 30px;\r\n");
      out.write("	max-width: 450px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .logo {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .logo i {\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	color: #0dcaf0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box h3 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("	color: #232884;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	transition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("	border-color: #0dcaf0;\r\n");
      out.write("	box-shadow: 0 0 5px rgba(13, 202, 240, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-info {\r\n");
      out.write("	background: #232884;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 50px;\r\n");
      out.write("	padding: 10px 25px;\r\n");
      out.write("	transition: 0.3s;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-info:hover {\r\n");
      out.write("	background: #0bb4d8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".small-links {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".small-links a {\r\n");
      out.write("	color: #232884;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".small-links a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"login-box\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<img src=\"../images/blacklogo.png\"\r\n");
      out.write("				style=\"width: 150px; height: auto;\">\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<h3>Worker Signup</h3>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"../WorkerSignupServlet\" method=\"post\"\r\n");
      out.write("			enctype=\"multipart/form-data\"\r\n");
      out.write("			class=\"p-4 border rounded shadow-sm bg-light\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"name\" class=\"form-label\">Name</label> <input type=\"text\"\r\n");
      out.write("					name=\"name\" class=\"form-control\" placeholder=\"Enter your name\"\r\n");
      out.write("					required />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"email\" class=\"form-label\">Email</label> <input\r\n");
      out.write("					type=\"email\" name=\"email\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"Enter your email\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"password\" class=\"form-label\">Password</label> <input\r\n");
      out.write("					type=\"password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"Create a password\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"gender\" class=\"form-label\">Gender</label> <select\r\n");
      out.write("					class=\"form-select\" name=\"gender\" required>\r\n");
      out.write("					<option value=\"\" disabled selected>Select Gender</option>\r\n");
      out.write("					<option>Male</option>\r\n");
      out.write("					<option>Female</option>\r\n");
      out.write("					<option>Other</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"service_id\" class=\"form-label\">Service</label> <select\r\n");
      out.write("					name=\"service_id\" id=\"service\" class=\"form-select\"\r\n");
      out.write("					onchange=\"toggleExtraFields()\" required>\r\n");
      out.write("					<option value=\"\">-- Select Service --</option>\r\n");
      out.write("					");

					Connection con = DBConnection.getConnection();
					PreparedStatement ps = con.prepareStatement("SELECT * FROM services");
					ResultSet rs = ps.executeQuery();
					while (rs.next()) {
					
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print(rs.getInt("service_id"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("service_name"));
      out.write("</option>\r\n");
      out.write("					");

					}
					con.close();
					
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Cook Options -->\r\n");
      out.write("			<div id=\"cookOptions\" class=\"mb-3\" style=\"display: none;\">\r\n");
      out.write("				<label class=\"form-label\">Veg/Non-Veg Preference</label> <select\r\n");
      out.write("					name=\"veg_pref\" class=\"form-select\">\r\n");
      out.write("					<option value=\"Veg\">Veg</option>\r\n");
      out.write("					<option value=\"Non-Veg\">Non-Veg</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Maid Options -->\r\n");
      out.write("			<div id=\"maidOptions\" class=\"mb-3\" style=\"display: none;\">\r\n");
      out.write("				<label class=\"form-label\">Maid Type</label> <input type=\"text\"\r\n");
      out.write("					name=\"maid_type\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"e.g., Full-time, Part-time\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Driver Options -->\r\n");
      out.write("			<div id=\"driverOptions\" class=\"mb-3\" style=\"display: none;\">\r\n");
      out.write("				<label class=\"form-label\">Driver Type</label> <select\r\n");
      out.write("					name=\"driver_type\" class=\"form-select\">\r\n");
      out.write("					<option value=\"Car\">Car</option>\r\n");
      out.write("					<option value=\"Bike\">Bike</option>\r\n");
      out.write("					<option value=\"Other\">Other</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Tutor Options -->\r\n");
      out.write("			<div id=\"tutorOptions\" class=\"mb-3\" style=\"display: none;\">\r\n");
      out.write("				<label class=\"form-label\">Subjects</label> <input type=\"text\"\r\n");
      out.write("					name=\"tutor_subject\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"e.g., Math, English\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label class=\"form-label\">Address</label> <input type=\"text\"\r\n");
      out.write("					name=\"address\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"Enter your address\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label class=\"form-label\">Contact</label> <input type=\"text\"\r\n");
      out.write("					name=\"contact\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"Enter your contact number\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-4\">\r\n");
      out.write("				<label class=\"form-label\">Upload Photo</label> <input type=\"file\"\r\n");
      out.write("					name=\"photo\" class=\"form-control\" accept=\"image/*\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"d-grid\">\r\n");
      out.write("				<input class=\"btn btn-success btn-lg\" type=\"submit\" value=\"Signup\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"small-links mt-3\">\r\n");
      out.write("			<a href=\"login.jsp\">Login here</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
