/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-25 13:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- basic -->\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- mobile metas -->\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\n");
      out.write("<!-- site metas -->\n");
      out.write("<title>Contact</title>\n");
      out.write("<meta name=\"keywords\" content=\"\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<!-- bootstrap css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\n");
      out.write("<!-- style css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("<!-- Responsive-->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("<!-- fevicon -->\n");
      out.write("<link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\n");
      out.write("<!-- fonts -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:400,700|Sen:400,700,800&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- Scrollbar Custom CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\n");
      out.write("<!-- Tweaks for older IEs-->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"header_section\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\"> <img\n");
      out.write("					src=\"images/logo.png\" style=\"width: 200px; height: auto;\">\n");
      out.write("				</a>\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#navbarSupportedContent\"\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("					aria-label=\"Toggle navigation\">\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("				</button>\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Home</a></li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">About</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Service</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Plans</a></li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Domain</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"other.jsp\">Other\n");
      out.write("								Services</a></li>\n");
      out.write("						<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("							href=\"contact.jsp\">Contact Us</a></li>\n");
      out.write("					</ul>\n");
      out.write("					<form class=\"form-inline my-2 my-lg-0\"></form>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("			<div class=\"custom_bg\">\n");
      out.write("				<div class=\"custom_menu\">\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("						<li><a href=\"index.jsp\">About</a></li>\n");
      out.write("						<li><a href=\"index.jsp\">Services</a></li>\n");
      out.write("						<li><a href=\"index.jsp\">Plans</a></li>\n");
      out.write("						<li><a href=\"index.jsp\">Domain</a></li>\n");
      out.write("						<li><a href=\"other.jsp\">Other Service</a></li>\n");
      out.write("						<li class=\"active\"><a href=\"contact.jsp\">Contact Us</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("					<div class=\"search_btn\">\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-search\"\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-shopping-cart\"\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- header section end -->\n");
      out.write("	<!-- contact section start -->\n");
      out.write("	<div class=\"contact_section layout_padding\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-sm-12\">\n");
      out.write("					<h1 class=\"contact_taital\">Contact Us</h1>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"contact_section_2\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-12\">\n");
      out.write("						<div class=\"mail_section_1\">\n");
      out.write("							<input type=\"text\" class=\"mail_text\" placeholder=\"Your Name\"\n");
      out.write("								name=\"Your Name\"> <input type=\"text\" class=\"mail_text\"\n");
      out.write("								placeholder=\"Your Email\" name=\"Your Email\"> <input\n");
      out.write("								type=\"text\" class=\"mail_text\" placeholder=\"Your Phone\"\n");
      out.write("								name=\"Your Phone\">\n");
      out.write("							<textarea class=\"massage-bt\" placeholder=\"Your Massage\" rows=\"5\"\n");
      out.write("								id=\"comment\" name=\"Your Massage\"></textarea>\n");
      out.write("							<div class=\"send_bt\">\n");
      out.write("								<a href=\"#\">Send Now</a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- contact section end -->\n");
      out.write("	<!-- footer section start -->\n");
      out.write("	<div class=\"footer_section layout_padding\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<h3 class=\"footer_text\">Service Provider</h3>\n");
      out.write("					<div class=\"footer_menu\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#\">We Provide Experience<br>Worker\n");
      out.write("									here.\n");
      out.write("							</a></li>\n");
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<h3 class=\"footer_text\">Address</h3>\n");
      out.write("					<div class=\"location_text\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-map-marker\" aria-hidden=\"true\"></i></span>Scheme 78,\n");
      out.write("									Vijay Nagar<br> Indore\n");
      out.write("							</a></li>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-phone\" aria-hidden=\"true\"></i></span>+91 8789878987\n");
      out.write("							</a></li>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-envelope\" aria-hidden=\"true\"></i></span>serviceprovider@gmail.com\n");
      out.write("							</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<div class=\"footer_main\">\n");
      out.write("						<h3 class=\"footer_text\">Find Us</h3>\n");
      out.write("						<div class=\"social_icon\">\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-facebook\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-twitter\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-instagram\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- footer section end -->\n");
      out.write("	<!-- copyright section start -->\n");
      out.write("	<div class=\"copyright_section\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<p class=\"copyright_text\">2024 All Rights Reserved. Distributed\n");
      out.write("				by Service Provider</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- copyright section end -->\n");
      out.write("	<!-- Javascript files-->\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<script src=\"js/jquery-3.0.0.min.js\"></script>\n");
      out.write("	<script src=\"js/plugin.js\"></script>\n");
      out.write("	<!-- sidebar -->\n");
      out.write("	<script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("	<script src=\"js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
