/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-26 06:15:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- basic -->\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- mobile metas -->\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\n");
      out.write("<!-- site metas -->\n");
      out.write("<title>Service Provider</title>\n");
      out.write("<meta name=\"keywords\" content=\"\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<!-- bootstrap css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\n");
      out.write("<!-- style css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("<!-- Responsive-->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("<!-- fevicon -->\n");
      out.write("<link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\n");
      out.write("<!-- fonts -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:400,700|Sen:400,700,800&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- Scrollbar Custom CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\n");
      out.write("<!-- Tweaks for older IEs-->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"header_section\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\"> <img\n");
      out.write("					src=\"images/logo.png\" style=\"width: 200px; height: auto;\">\n");
      out.write("				</a>\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#navbarSupportedContent\"\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("					aria-label=\"Toggle navigation\">\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("				</button>\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\n");
      out.write("						<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("							href=\"index.jsp\">Home</a></li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#about\">About</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#service\">Service</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#plan\">Plans</a></li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Domain</a>\n");
      out.write("						</li> \n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"other.jsp\">Other Services</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.jsp\">Contact\n");
      out.write("								Us</a></li>\n");
      out.write("					</ul>\n");
      out.write("					<form class=\"form-inline my-2 my-lg-0\"></form>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("			<div class=\"custom_bg\">\n");
      out.write("				<div class=\"custom_menu\">\n");
      out.write("					<ul>\n");
      out.write("						<li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("						<li><a href=\"#about\">About</a></li>\n");
      out.write("						<li><a href=\"#service\">Services</a></li>\n");
      out.write("						<li><a href=\"#plan\">Plans</a></li>\n");
      out.write("						<li><a href=\"#\">Domain</a></li>\n");
      out.write("						<li><a href=\"other.jsp\">Other Service</a></li>\n");
      out.write("						<li><a href=\"contact.jsp\">Contact Us</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("					<div class=\"search_btn\">\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-search\"\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-shopping-cart\"\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- banner section start -->\n");
      out.write("		<div class=\"banner_section layout_padding\">\n");
      out.write("			<div id=\"my_slider\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("				<div class=\"carousel-inner\">\n");
      out.write("					<div class=\"carousel-item active\">\n");
      out.write("						<div class=\"container\">\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<h1 class=\"banner_taital\">\n");
      out.write("										Book Your Services<br>Here....!\n");
      out.write("									</h1>\n");
      out.write("									<div class=\"read_bt\">\n");
      out.write("										<a href=\"user/login.jsp\">Book Now</a>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"banner_img\">\n");
      out.write("										<img src=\"images/main.png\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- banner section end -->\n");
      out.write("	</div>\n");
      out.write("	<!-- header section end -->\n");
      out.write("\n");
      out.write("	<!-- pricing section start -->\n");
      out.write("	<div class=\"pricing_section layout_padding\" id=\"plan\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-12\">\n");
      out.write("					<h1 class=\"pricing_taital\">Our Plans</h1>\n");
      out.write("					<p class=\"pricing_text\">Unlock all features and get full access by choosing a plan that suits you best.</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"pricing_section_2\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-4\">\n");
      out.write("						<div class=\"pricing_box\">\n");
      out.write("							<h3 class=\"number_text\">1</h3>\n");
      out.write("							<h1 class=\"dolor_text\">99/-</h1>\n");
      out.write("							<h3 class=\"monthly_text\">1-MONTH</h3>\n");
      out.write("							<p class=\"band_text\">Up to 3 Services<br>Experienced Workers<br>Priority Support<br>7 Days Replacement</p>\n");
      out.write("							<div class=\"signup_bt\">\n");
      out.write("								<a href=\"#\">Buy</a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-4\">\n");
      out.write("						<div class=\"pricing_box\">\n");
      out.write("							<h3 class=\"number_text\">2</h3>\n");
      out.write("							<h1 class=\"dolor_text\">149/-</h1>\n");
      out.write("							<h3 class=\"monthly_text\">3-MONTHS</h3>\n");
      out.write("							<p class=\"band_text\">Up to 3 Services<br>Experienced Workers<br>Priority Support<br>7 Days Replacement</p>\n");
      out.write("							<div class=\"signup_bt\">\n");
      out.write("								<a href=\"#\">Buy</a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-4\">\n");
      out.write("						<div class=\"pricing_box\">\n");
      out.write("							<h3 class=\"number_text\">3</h3>\n");
      out.write("							<h1 class=\"dolor_text\">249/-</h1>\n");
      out.write("							<h3 class=\"monthly_text\">6-MONTHS</h3>\n");
      out.write("							<p class=\"band_text\">Up to 3 Services<br>Experienced Workers<br>Priority Support<br>7 Days Replacement</p>\n");
      out.write("							<div class=\"signup_bt\">\n");
      out.write("								<a href=\"#\">Buy</a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- pricing section end -->\n");
      out.write("	<!-- services section start -->\n");
      out.write("	<div class=\"services_section layout_padding\" id=\"service\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-12\">\n");
      out.write("					<h1 class=\"services_taital\">Our Services</h1>\n");
      out.write("					<p class=\"services_text\">Providing Expert Workers You Can Trust\n");
      out.write("						For Every Task, Big or Small.</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"services_section_2\">\n");
      out.write("				<div id=\"main_slider\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("					<div class=\"carousel-inner\">\n");
      out.write("						<div class=\"carousel-item active\">\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-4\">\n");
      out.write("									<div class=\"service_box\">\n");
      out.write("										<div class=\"services_icon\">\n");
      out.write("											<img src=\"images/maidSer.png\" class=\"image_1\"><img\n");
      out.write("												src=\"images/maidSer.png\" class=\"image_2\">\n");
      out.write("										</div>\n");
      out.write("										<h3 class=\"wordpress_text\">Maid</h3>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-4\">\n");
      out.write("									<div class=\"service_box\">\n");
      out.write("										<div class=\"services_icon\">\n");
      out.write("											<img src=\"images/teachSer.png\" class=\"image_1\"><img\n");
      out.write("												src=\"images/teachSer.png\" class=\"image_2\">\n");
      out.write("										</div>\n");
      out.write("										<h3 class=\"wordpress_text\">Cook</h3>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-4\">\n");
      out.write("									<div class=\"service_box\">\n");
      out.write("										<div class=\"services_icon\">\n");
      out.write("											<img src=\"images/driverSer.png\" class=\"image_1\"><img\n");
      out.write("												src=\"images/driverSer.png\" class=\"image_2\">\n");
      out.write("										</div>\n");
      out.write("										<h3 class=\"wordpress_text\">Driver</h3>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- services section end -->\n");
      out.write("	<!-- testimonial section start -->\n");
      out.write("	<div class=\"testimonial_section layout_padding\" id=\"about\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\n");
      out.write("				data-ride=\"carousel\">\n");
      out.write("				<ol class=\"carousel-indicators\">\n");
      out.write("					<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\n");
      out.write("						class=\"active\"></li>\n");
      out.write("					<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("					<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("				</ol>\n");
      out.write("				<div class=\"carousel-inner\">\n");
      out.write("					<div class=\"carousel-item active\">\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-md-12\">\n");
      out.write("								<h1 class=\"testimonial_taital\">About</h1>\n");
      out.write("								<p class=\"testimonial_text\">Your comfort, our priority. Experience professional service\n");
      out.write("										like never before!</p>\n");
      out.write("								<div class=\"testimonial_section_2\">\n");
      out.write("									<p class=\"ipsum_text\">We provide trusted and experienced\n");
      out.write("										workers for your everyday needs. Whether you are looking for a\n");
      out.write("										maid to keep your home clean, a cook to prepare delicious\n");
      out.write("										meals, a home tutor for your childs academic support, or a\n");
      out.write("										driver to help you travel safely we have got you covered.\n");
      out.write("										Our platform connects you with skilled, verified, and reliable\n");
      out.write("										professionals who are trained to deliver quality services with\n");
      out.write("										honesty and dedication. We aim to make your life easier by\n");
      out.write("										providing affordable, convenient, and efficient home services,\n");
      out.write("										all in one place. With our growing network of workers, you can\n");
      out.write("										also find babysitters, elderly care staff, electricians,\n");
      out.write("										plumbers, and many more whenever and wherever you need them.\n");
      out.write("\n");
      out.write("										Your comfort, our priority. Experience professional service\n");
      out.write("										like never before!</p>\n");
      out.write("									<div class=\"quick_img\">\n");
      out.write("										<img src=\"images/quick-icon.png\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"client_img\">\n");
      out.write("									<img src=\"images/owner.png\"\n");
      out.write("										style=\"width: 200px; height: 200px; border-radius: 50%;\">\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<h4 class=\"client_name\">Yash Surma</h4>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- testimonial section end -->\n");
      out.write("	<!-- footer section start -->\n");
      out.write("	<div class=\"footer_section layout_padding\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<h3 class=\"footer_text\">Service Provider</h3>\n");
      out.write("					<div class=\"footer_menu\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#\">We Provide Experience<br>Worker here.\n");
      out.write("							</a></li>\n");
      out.write("							\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<h3 class=\"footer_text\">Address</h3>\n");
      out.write("					<div class=\"location_text\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-map-marker\" aria-hidden=\"true\"></i></span>Scheme 78, Vijay Nagar<br> Indore\n");
      out.write("							</a></li>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-phone\" aria-hidden=\"true\"></i></span>+91 8789878987\n");
      out.write("							</a></li>\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\n");
      out.write("										class=\"fa fa-envelope\" aria-hidden=\"true\"></i></span>serviceprovider@gmail.com\n");
      out.write("							</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-sm-4\">\n");
      out.write("					<div class=\"footer_main\">\n");
      out.write("						<h3 class=\"footer_text\">Find Us</h3>\n");
      out.write("						<div class=\"social_icon\">\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-facebook\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-twitter\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-instagram\"\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- footer section end -->\n");
      out.write("	<!-- copyright section start -->\n");
      out.write("	<div class=\"copyright_section\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<p class=\"copyright_text\">\n");
      out.write("				2024 All Rights Reserved. Distributed by Service Provider\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- copyright section end -->\n");
      out.write("	<!-- Javascript files-->\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<script src=\"js/jquery-3.0.0.min.js\"></script>\n");
      out.write("	<script src=\"js/plugin.js\"></script>\n");
      out.write("	<!-- sidebar -->\n");
      out.write("	<script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("	<script src=\"js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
