/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-26 05:37:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class other_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- basic -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- mobile metas -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<!-- site metas -->\r\n");
      out.write("<title>Service Provider</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<!-- bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<!-- Responsive-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- fevicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\r\n");
      out.write("<!-- fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:400,700|Sen:400,700,800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Scrollbar Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("<!-- Tweaks for older IEs-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header_section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\"> <img\r\n");
      out.write("					src=\"images/logo.png\" style=\"width: 200px; height: auto;\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\"#navbarSupportedContent\"\r\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">About</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Service</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Plans</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Domain</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">Other Services</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("							href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<form class=\"form-inline my-2 my-lg-0\"></form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"custom_bg\">\r\n");
      out.write("				<div class=\"custom_menu\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("						<li><a href=\"index.jsp\">About</a></li>\r\n");
      out.write("						<li><a href=\"index.jsp\">Services</a></li>\r\n");
      out.write("						<li><a href=\"index.jsp\">Plans</a></li>\r\n");
      out.write("						<li><a href=\"index.jsp\">Domain</a></li>\r\n");
      out.write("						<li class=\"active\"><a href=\"#\">Other Service</a></li>\r\n");
      out.write("						<li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("					<div class=\"search_btn\">\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-search\"\r\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-shopping-cart\"\r\n");
      out.write("								aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- header section end -->\r\n");
      out.write("	<!-- footer section start -->\r\n");
      out.write("	<div class=\"footer_section layout_padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<h3 class=\"footer_text\">Service Provider</h3>\r\n");
      out.write("					<div class=\"footer_menu\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"active\"><a href=\"admin/login.jsp\"><span\r\n");
      out.write("									class=\"angle_icon active\"><i class=\"fa fa-arrow-right\"\r\n");
      out.write("										aria-hidden=\"true\"></i></span> Admin Service</a></li>\r\n");
      out.write("							<li><a href=\"index.jsp\"><span class=\"angle_icon\"><i\r\n");
      out.write("										class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i></span> Home</a></li>\r\n");
      out.write("							<li><a href=\"index.jsp\"><span class=\"angle_icon\"><i\r\n");
      out.write("										class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i></span> Services</a></li>\r\n");
      out.write("							<li><a href=\"index.jsp\"><span class=\"angle_icon\"><i\r\n");
      out.write("										class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i></span> Plans</a></li>\r\n");
      out.write("							<li><a href=\"worker/login.jsp\"><span class=\"angle_icon\"><i\r\n");
      out.write("										class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i></span> Worker Service</a></li>\r\n");
      out.write("							<li><a href=\"index.jsp\"><span class=\"angle_icon\"><i\r\n");
      out.write("										class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i></span> Contact Us</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<h3 class=\"footer_text\">Address</h3>\r\n");
      out.write("					<div class=\"location_text\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\r\n");
      out.write("										class=\"fa fa-map-marker\" aria-hidden=\"true\"></i></span>Scheme 78,\r\n");
      out.write("									Vijay Nagar<br> Indore\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\r\n");
      out.write("										class=\"fa fa-phone\" aria-hidden=\"true\"></i></span>+91 8789878987\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\"> <span class=\"padding_left_10\"><i\r\n");
      out.write("										class=\"fa fa-envelope\" aria-hidden=\"true\"></i></span>serviceprovider@gmail.com\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<div class=\"footer_main\">\r\n");
      out.write("						<h3 class=\"footer_text\">Find Us</h3>\r\n");
      out.write("						<div class=\"social_icon\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-facebook\"\r\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-twitter\"\r\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"fa fa-instagram\"\r\n");
      out.write("										aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- footer section end -->\r\n");
      out.write("	<!-- copyright section start -->\r\n");
      out.write("	<div class=\"copyright_section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<p class=\"copyright_text\">2024 All Rights Reserved. Distributed\r\n");
      out.write("				by Service Provider</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- copyright section end -->\r\n");
      out.write("	<!-- Javascript files-->\r\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery-3.0.0.min.js\"></script>\r\n");
      out.write("	<script src=\"js/plugin.js\"></script>\r\n");
      out.write("	<!-- sidebar -->\r\n");
      out.write("	<script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("	<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
